import '@/styles/tailwind.css'
import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from "next/head";

import Layout from '../components/Layout'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;


export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>ImmVis</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<Component {...pageProps} />
			</Layout>
		</>
	);
}
